### ISSUE TITLE
Characters escaped are inadequate

### ISSUE THREAD

**Issue by rnewman** [component/escape-html#23]
Hey folks,

I was poking around for a thorough escaping lib, and looked at the source for `escape-html`. I noticed it only escapes quotes, ampersand, and angle brackets:

https://github.com/component/escape-html/blob/master/index.js#L16

This isn't adequate for handling arbitrary content; I'll point you to a good article by Ryan Grove from five years ago, rather than making all the points myself.

http://wonko.com/post/html-escaping

**Comment by dougwilson** [comment]
Thanks for the link! I speed read through it but I don't see a good conclusion besides "context is key", and this is currently a context-free function.

What are your suggestions on how to change/improve this module? Would you be willing to out together a proposal & pull request?

**Comment by rnewman** [comment]
I'm sorry, I don't have the time to make substantial contributions here.

You might consider broadening the set of escaped characters (which will alter the behavior of the library for some common characters), and/or documenting the limitations: the primary issues are around using `escape-html` to escape user input for use in attribute values or `<script>` tags, so if consumers of this library don't do that, then they're likely to be safe.

**Comment by dougwilson** [comment]
Thanks @rnewman, I'll see what I can come up with. I would really appreciate it if you could provide some specific thoughts, because I'm sure you had some to open this issue, and I don't want to close it unless I addressed your concerns, and at this point, I'm not sure what your concerns are besides "change something".

As an example, you said "You might consider broadening the set of escaped characters". Ok, but how do I know if I've satisfied your desire here? Which characters should I add? The article you linked to has no recommendations, just progressively demonstrates that escaping it not a one-size-fits-all, and does not actually provide rules on which are good generic characters to escape. I believe this module originally copied things like the common PHP escaping.

Does this mean that the only real change here is adding documentation to describe the context in which one can use the escaped value (i.e. only within HTML tag content, excluding tags that have different escape semantics like script & style, or within quoted attribute values)?

**Comment by rnewman** [comment]
There's no single concrete best thing to do; this is all about tradeoffs, and I'm not familiar with the users of this library, so I'm not in a good place to make a single recommendation.

I filed this issue because I clicked through to the source, said to myself "oh jeez, this library is downloaded 300,000 times a day; I should at least spend the time to file an issue". There will be *some* apps *somewhere* that use this library for escaping user input and inserting it as an attribute value, and those apps are vulnerable because `escape-html` isn't safe for attributes.

The easiest thing to do is to add a big note to the `README` pointing out that this tiny library *only* escapes `[<>&"']`, and that as such it's only safe for use for generating element content, or for quoted attribute values not served to IE browsers — that is, to require users to understand how the library works and when it should be used. That's not likely to help the install base; they won't come back and read the `README`, and developers will still make mistakes.

The 'correct' thing to do is to also escape `&`, `<`, `>`, `"`, `'`, ```, `SPACE`, `!`, `@`, `$`, `%`, `(`, `)`, `=`, `+`, `{`, `}`, `[`, and `]`, as that blog post notes. Yes, that means escaping space characters. That's probably overkill and surprising for many consumers.

You could get close to correct by escaping most of those characters but excluding space, and requiring callers to quote their attribute values — folks who don't are already asking for trouble.

A middle ground might be to find some way of deprecating the existing function, and provide two new ones: one for element content and one for attributes. I'm not familiar with how the modern JS ecosystem handles deprecation warnings.

Another thing you could do is decide that this library is already culturally understood to be only useful for element content, and close this issue.

There's no right answer. This is something that a framework should expose, that a type system should define and detect, or that the lingua franca of the web should include… but none of those things are true in JS, so here we are.

**Comment by dougwilson** [comment]
> The 'correct' thing to do is to also escape  & ,  < ,  > ,  " ,  ' , backtick, space,  ! ,  @ ,  $ ,  % ,  ( ,  ) ,  = ,  + ,  { ,  } ,  [ , and  ] , as that blog post notes.

Are we reading the same article? It still says that is not enough. Looking in your public github history, you are commenting on a pull request that uses a different html escape module that also escapes none of these extra characters. Can your lease make this same issue for that module so I can follow along the discussion that authors has?

> There's no right answer.

Right, and that's where we are. At this point, I truthfully have no good idea how you want me to resolve this issue. I will update the README with my best guess here and close the issue, and if you have any further suggestions, make a pull request or provide a specific recommendation :)

**Comment by dougwilson** [comment]
So I updated the README with my best guess at what you are looking for. The reasoning for the change is that, based on the article you linked to, the point is that there is no one-size-fits-all for escaping, and that the context of where the string is going to end up is key ("context is key", as the article puts it). On that line, I made the following two changes:

1. I described what character are being escaped, to make it easier than clicking to open the source (even though it's open).
2. I tried to describe what context is appropriate for this module's escaped string to be used in.

I hope that this helps with the concern for opening the issue. If you have any additional suggestions, please feel free to make a pull request or provide a specific recommendation :) And I'm sure we can get it added in!

**Comment by rnewman** [comment]
Looks like you found a good approach, Doug!
