### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [component/escape-html#27]
[This package](https://www.jsdelivr.com/package/npm/escape-html) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by dougwilson** [comment]
The package.json format defaults the "index.js" as the default when not specified. I don't specify the fields in which the default value is the one I want to use :)

You can see what I mean at https://nodejs.org/dist/latest-v12.x/docs/api/modules.html

> If there is no package.json file present in the directory, or if the 'main' entry is missing or cannot be resolved, then Node.js will attempt to load an index.js or index.node file out of that directory.

**Comment by dougwilson** [comment]
I'm not sure about jsDeliver, but this is just a module meant for Node.js consumption and I just publish it to npm registry.
